### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by pbou** [dccastro/NDFlow#1]
Thanks for sharing your code.
It works for about half of my images, but for the other half, I get this:
/usr/local/lib/python3.6/dist-packages/ndflow/warping/flow.py:28: RuntimeWarning: invalid value encountered in true_divide
  post_k = pi[k] * q_k / q

**Comment by dccastro** [comment]
That sounds like a division by zero, maybe caused by numerical underflow in `q`. I can imagine this happening if some pixels are much brighter or darker than most of the image.
I've never encountered this warning with the datasets on which I've applied NDFlow, however. Try checking if the images causing this have intensities in a reasonable range (e.g. check for corrupted pixels, artefacts).

**Comment by pbou** [comment]
Thanks. I've checked the images, and can't see any voxels much brighter. Actually, in one case, I have 4 repeats of the same patients on the same scanner, and 2 out of 4 failed. 
One thing I've found is that the dynamic range seems to cause issues. After the BF correction, my images are scaled between 0 and ~5. If I increase this (multiplying the images by 500), it seems to get rid of the error? The only thing I can think of is that somewhere in the code, floats might be casted to integer?

**Comment by dccastro** [comment]
Yes, excellent catch! As documented [here](https://github.com/dccastro/NDFlow/blob/986d7fffe8d0cc4ade3b8095dea5b5ce1a82aee7/ndflow/api.py#L46-L48) in `ndflow.estimate()`, the default behaviour is to cast to integer.
If you're using the API directly, you can customise the quantisation by just passing e.g. `levels=200` to this function. If you're using the command-line scripts, I'm happy to add a `--levels` option, which is currently missing.
I'll try to make this default behaviour more obvious in the README.

**Comment by pbou** [comment]
Good to know. Thanks.
I am using the scripts, so if you don't mind adding the `--levels` option, that would be much appreciated.

**Comment by dccastro** [comment]
Just added the option in commit 9d5280e520f194b235353ead32378fe9b945e890.
Thanks for using our code and for flagging this unexpected behaviour!
